branch-defaults:
  default:
    environment: Udagram1-env
    group_suffix: null
deploy:
  artifact: www/Archive.zip

global:
  application_name: Udagram1
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: null
  workspace_type: Application
